---
# Use images from Ark.
{% if stackhpc_download_overcloud_images | bool %}
use_cirros: true
{% if os_distribution == 'ubuntu' %}
cirros_deploy_image_upstream_url: "{{ stackhpc_ubuntu_overcloud_host_image_url }}"
{% elif os_distribution == 'rocky' %}
cirros_deploy_image_upstream_url: "{{ stackhpc_rocky_overcloud_host_image_url }}"
{% else %}
cirros_deploy_image_upstream_url: "{{ stackhpc_centos_overcloud_host_image_url }}"
{% endif %}
{% endif %}
