---
sources:
  - name: pollsters
    interval: 300
    meters:
      - cpu
      - image.size
      - ip.floating
      - network.incoming.bytes
      - network.outgoing.bytes
      - snapshot.size
      - volume.backup.size
      - volume.size
      - volume.snapshot.size
