---
- name: Gather Ceph configuration and keys and populate kayobe-config
  gather_facts: false
  hosts: mons
  run_once: true
  vars:
    # Map from an OpenStack service to the directory in which to store Ceph keys for it.
    kolla_service_to_key_dir:
      cinder-backup: cinder/cinder-backup
      cinder-volume: cinder/cinder-volume
      glance: glance
      nova: nova
    # Map from an OpenStack service to the directory in which to store Ceph configuration for it.
    kolla_service_to_conf_dir:
      cinder-backup: cinder
      cinder-volume: cinder
      glance: glance
      nova: nova
  tasks:
    - name: Get Ceph keys
      stackhpc.cephadm.cephadm_key:
        name: "{{ item.name }}"
        state: info
      register: cephadm_key_info
      become: true
      loop: "{{ cephadm_keys }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.state | default != 'absent'

    - name: Generate ceph.conf
      command: "cephadm shell -- ceph config generate-minimal-conf"
      become: true
      register: cephadm_ceph_conf
      changed_when: false

    - name: Ensure Kolla config directories are present
      file:
        state: directory
        path: "{{ kayobe_env_config_path }}/kolla/config/{{ kolla_service_to_key_dir[item.1] }}"
      loop: "{{ query('subelements', cephadm_keys, 'kolla_services', skip_missing=True) }}"
      loop_control:
        label:
          key: "{{ item.0.name }}"
          service: "{{ item.1 }}"
      when: item.0.state | default != 'absent'
      delegate_to: localhost

    - name: Save Ceph keys to Kayobe configuration
      vars:
        key_info: "{{ cephadm_key_info.results | selectattr('item.name', 'equalto', item.0.name) | first }}"
        cephadm_key: "{{ (key_info.stdout | from_json | first)['key'] }}"
        cephadm_user: "{{ (key_info.stdout | from_json | first)['entity'] }}"
      copy:
        content: "{{ cephadm_key }}"
        dest: "{{ kayobe_env_config_path }}/kolla/config/{{ kolla_service_to_key_dir[item.1] }}/ceph.{{ cephadm_user }}.keyring"
      loop: "{{ query('subelements', cephadm_keys, 'kolla_services', skip_missing=True) }}"
      loop_control:
        label:
          key: "{{ item.0.name }}"
          service: "{{ item.1 }}"
      when: item.0.state | default != 'absent'
      delegate_to: localhost
      notify: Please add and commit the Kayobe configuration

    - name: Save ceph.conf to Kayobe configuration
      copy:
        content: "{{ cephadm_ceph_conf.stdout }}"
        dest: "{{ kayobe_env_config_path }}/kolla/config/{{ kolla_service_to_conf_dir[item.1] }}/ceph.conf"
      loop: "{{ query('subelements', cephadm_keys, 'kolla_services', skip_missing=True) }}"
      loop_control:
        label:
          key: "{{ item.0.name }}"
          service: "{{ item.1 }}"
      when: item.0.state | default != 'absent'
      delegate_to: localhost
      notify: Please add and commit the Kayobe configuration

  handlers:
    - name: Please add and commit the Kayobe configuration
      debug:
        msg: >-
          Please add and commit the Ceph configuration files and keys in Kayobe
          configuration. Remember to encrypt the keys using Ansible Vault.
