---
# Build an image for the ha-cluster-exporter Prometheus exporter and push it to
# the local registry.
- name: Ensure HACluster container image is built
  hosts: container-image-builders
  tasks:
    - name: Create a temporary directory
      tempfile:
        state: directory
      register: tempfile_result

    - name: Set path facts
      vars:
        work_path: "{{ tempfile_result.path }}"
      set_fact:
        src_path: "{{ work_path }}/octavia"
        work_path: "{{ work_path }}"

    - block:
        - name: Clone ha-cluster-exporter-image repository
          git:
            repo: "https://greenedge:{{ kolla_git_pat_token }}@dev.azure.com/greenedge/cloud/_git/ha-cluster-exporter-image"
            dest: "{{ src_path }}/ha-cluster-exporter"

        - name: Login to docker registry
          docker_login:
            registry_url: "{{ docker_registry }}"
            username: "{{ kolla_docker_registry_username }}"
            password: "{{ kolla_docker_registry_password }}"
            reauthorize: yes
          when:
            - kolla_docker_registry_username is not none
            - kolla_docker_registry_password is not none

        - name: Ensure ha-cluster-exporter container image is built
          docker_image:
            name: "{{ docker_registry }}/leafcloud/ha-cluster-exporter"
            build:
              path: "{{ src_path }}/ha-cluster-exporter"
            push: true
            source: build
            state: present
      always:
        - name: Remove temporary files
          file:
            path: "{{ work_path }}"
            state: absent
