---
- name: Ensure NIC drivers are installed
  hosts: controllers:compute
  tasks:
    - name: Ensure ELRepo repository is installed
      become: true
      package:
        name: elrepo-release
    - name: Upgrade all packeges
      become: true
      dnf:
        name: "*"
        state: latest
    - name: Ensure NIC drivers are installed
      become: true
      package:
        name: kmod-be2net
      notify:
        - Reboot and wait

  handlers:
    - name: Reboot and wait
      become: true
      reboot:
