---
- name: Register an Octavia Amphora image in Glance
  gather_facts: no
  hosts: seed
  vars:
    venv: "{{ virtualenv_path }}/octavia-amphora"
  tasks:
    - name: Fail if not using octavia user and service project
      fail:
        msg: >-
          Source the octavia-openrc.sh file before executing this playbook
      when: >-
        lookup('env', 'OS_USERNAME') != 'octavia' or
        lookup('env', 'OS_PROJECT_NAME') != 'service'

    - name: Set up openstack virtualenv
      pip:
        virtualenv: "{{ venv }}"
        name:
          - openstacksdk
          - python-openstackclient
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"

    - name: Ensure Octavia Amphora image is registered
      vars:
        ansible_python_interpreter: "{{ venv }}/bin/python"
      os_image:
        auth_type: password
        auth: "{{ openstack_auth }}"
        ca_cert: "{{ openstack_cacert }}"
        interface: "{{ openstack_interface }}"
        name: amphora-x64-haproxy.qcow2
        container_format: bare
        disk_format: qcow2
        is_public: no
        filename: "{{ image_cache_path }}/amphora-x64-haproxy.qcow2"
        properties:
          hw_architecture: x86_64
          hw_rng_model: virtio

    - name: Ensure Octavia Amphora image is tagged
      shell:
        cmd: >-
          {{ venv }}/bin/openstack image set amphora-x64-haproxy.qcow2 --tag amphora
      environment: "{{ openstack_auth_env }}"
