---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
roles:
  - name: wazuh-ansible
    src: https://github.com/wazuh/wazuh-ansible.git
    version: v4.3.6

