---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
  - name: stackhpc.cephadm
    version: 1.8.0
roles:
  - name: vxlan
    src: https://github.com/stackhpc/ansible-role-vxlan.git
