---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
  - name: ansible.utils
    version: 2.6.1
roles:
  - name: vxlan
    src: https://github.com/stackhpc/ansible-role-vxlan.git

