---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
  - name: stackhpc.cephadm
    version: 1.8.0
  - name: ansible.utils
    version: 2.6.1
roles:
  - src: stackhpc.vxlan
