---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
roles:
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible.git
    version: v4.2.3-opendistro-ubuntu
