---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: install passlib[bcrypt]
      pip:
        name: passlib[bcrypt]
        virtualenv: "{{ ansible_playbook_python | dirname | dirname }}"

    - name: Include existing secrets if they exist
      include_vars: ../inventory/group_vars/wazuh-master/wazuh-secrets.yml
      ignore_errors: true

    - name: Template new secrets
      template:
        src: wazuh-secrets.yml.j2
        dest: ../inventory/group_vars/wazuh-master/wazuh-secrets.yml
