global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: leafcloudalarms@gmail.com
  smtp_smarthost: smtp.gmail.com:465
  smtp_hello: localhost
  smtp_require_tls: true
  smtp_auth_username: leafcloudalarms@gmail.com
  smtp_auth_password:
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default-receiver
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
receivers:
  - name: default-receiver
    email_configs:
      - to: jegor@greenedge.cloud
templates: []